### ISSUE TITLE
Creating DataFrame from json that contains "index" key/property causes error

### ISSUE THREAD

**Issue by jeremydiviney** [opensource9ja/danfojs#57] opened 2020-11-24 23:40 UTC
The Following Code:
```
const jsonData = [{name:'test1',index: 0},{name:'test2',index: 1}]
const df = new dfd.DataFrame(jsonData);

```
This will cause the error: _UnhandledPromiseRejectionWarning: TypeError: Cannot set property index of [object Object] which has only a getter_

Looks like within the DataFrame class "index" is reserved

```

class DataFrame extends _generic.default {
  constructor(data, kwargs) {
    super(data, kwargs);

    this.__set_column_property();
  }
 __set_column_property() {
    let col_vals = this.col_data;
    let col_names = this.column_names;
    col_vals.forEach((col, i) => {
      this[col_names[i]] = null;   <<<< Error happens here
      Object.defineProperty(this, col_names[i], {
        get() {
          return new _series.Series(this.col_data[i], {
            columns: col_names[i],
            index: this.index
          });
        },

        set(value) {
          this.addColumn({
            column: col_names[i],
            value: value
          });
        }

      });
    });
  }
```

**Comment by risenW** [comment] 2020-11-25 10:17
Interesting issue. Thanks for raising this. We have to update the internal name for index then, maybe adding an underscore before the name (_index).  Would you like to fix this?

**Comment by mjarmoc** [comment] 2020-12-05 11:48
The same happens if `size` key is present in data.
```const jsonData = [{name:'test1',size: 0},{name:'test2',size: 1}]
const df = new dfd.DataFrame(jsonData);

**Comment by risenW** [comment] 2020-12-16 19:28
@mjarmoc Would you like to work on this?

**Comment by apokralipsa** [comment] 2021-01-28 17:15
I was looking into it, planning to use a Symbol instead of prefixing the field names to better avoid conflicts.
The issue is that the `index` property is exposed by the `NDframe` class and is documented [here](https://danfo.jsdata.org/api-reference/dataframe/dataframe.index). At the same time accessing columns by name is also documented [here](https://danfo.jsdata.org/getting-started#getting). I don't think it can be fixed without breaking backwards compatibility and changing one of those.

**Comment by HenrikPereira** [comment] 2021-03-28 02:32
Happened the same to me, but my JSON had a key named `data`... After change of this key on source to `data_c`, everything went ok.

**Closed** 2021-08-06 05:28 UTC
Labels: bug, good first issue, no-issue-activity
