### ISSUE TITLE
Error:  The Node.js native addon module (tfjs_binding.node) can not be found at path...

### ISSUE THREAD

**Issue by samiragol** [opensource9ja/danfojs#20] opened 2020-08-31 21:21 UTC
I am trying to install DanfoJS on **windows 10** using below command: 
```
npm install danfojs-node
```
but I get following error when I run ```npm start```

> Error: The Node.js native addon module (tfjs_binding.node) can not be found at path: 

I tried to ran ```npm rebuild @tensorflow/tfjs-node build-addon-from-source``` but still having problem.

**Comment by risenW** [comment] 2020-09-01 04:27
This error is from TFJS. I've noticed it for Windows users. Here's a link to a similar GitHub issue on the TFjs issues page, see if it works for you.
https://github.com/tensorflow/tfjs/issues/2046

**Comment by samiragol** [comment] 2020-09-01 16:16
I tried almost everything was mentioned on the issue page you forwarded, still having same problem :(

**Comment by samiragol** [comment] 2020-09-01 16:17
here is my package.json:

```
"devDependencies": {
    "babel-polyfill": "^6.26.0",
    "electron": "^10.1.0",
    "electron-packager": "^13.1.1"
  },
  "dependencies": {
    "@tensorflow/tfjs-node": "^2.3.0",
    "body-parser": "^1.18.3",
    "danfojs-node": "^0.1.4",
    "electron-log": "^3.0.6",
    "express": "^4.16.4",
    "local-devices": "^2.0.0",
    "node-thermal-printer": "^4.1.0",
    "react-select": "^3.1.0",
    "regenerator-runtime": "^0.13.5",
    "ws": "^7.2.0",
    "xml2js": "^0.4.22",
    "xpath": "0.0.27",
    "yargs": "^14.0.0"
  },
```

**Comment by risenW** [comment] 2020-09-01 16:28
I think I see the issue, danfo-node uses @tensorflow/tfjs-node": "^2.1.0", so I think it is conflicting with the current version. Try removing the @tensorflow/tfjs-node": "^2.3.0" dependencies and run npm install again

**Comment by samiragol** [comment] 2020-09-01 16:38
ok I did what you said and still having the same issue.  current package.json: 

```
  "devDependencies": {
    "babel-polyfill": "^6.26.0",
    "electron": "^10.1.0",
    "electron-packager": "^13.1.1"
  },
  "dependencies": {
    "@tensorflow/tfjs-node": "^2.1.0",
    "body-parser": "^1.18.3",
    "danfojs-node": "^0.1.4",
    "electron-log": "^3.0.6",
    "express": "^4.16.4",
    "local-devices": "^2.0.0",
    "node-thermal-printer": "^4.1.0",
    "react-select": "^3.1.0",
    "regenerator-runtime": "^0.13.5",
    "ws": "^7.2.0",
    "xml2js": "^0.4.22",
    "xpath": "0.0.27",
    "yargs": "^14.0.0"
  },
```

**Comment by risenW** [comment] 2020-09-01 16:44
I meant to remove the Tensorflow dependency and then run npm install

**Comment by samiragol** [comment] 2020-09-01 16:47
yeah I tried removing Tensorflow dependency first and I ran ```npm install``` I got same error and then I tried ```npm i @tensorflow/tfjs-node@2.1.0``` and still the same issue

**Comment by risenW** [comment] 2020-09-01 16:53
That's weird. Have you tried a clean start? you could start a new project in a different director, and try to install danfo-node without TensorFlow dependency added  Meanwhile, I'll try to replicate your issue here. What is your OS spec?

**Comment by samiragol** [comment] 2020-09-01 16:57
I tried deleting node_modules several times, with and without TensorFlow dependency. I'm on windows 10 x64.

**Comment by risenW** [comment] 2020-09-01 18:41
You can actually use Tensorflowjs with directly install it. Since it is a dependency of danfojs, it gets installed automatically. So I'm definitely sure the issue is coming from windows build. 
1. Try installing version 2.1.0 of Tensorflowjs and see if you can build it successfully.

If not, you may need to download the windows-build-tools (https://github.com/tensorflow/tfjs/blob/master/tfjs-node/WINDOWS_TROUBLESHOOTING.md#msbuildexe-exceptions

2. If you can successfully build TFjs, then, Do a clean start, and npm install danfojs-node in your project. Do not install Tensorflowjs again, and do not add it to the package.json file. You should be able to import and use it.

**Comment by samiragol** [comment] 2020-09-01 20:42
I did all these steps already and I just did it again since you asked me. Just to mention I have both python 2.7 and 3.8 and I suspect I have to set a default to target one of them.

**Comment by risenW** [comment] 2020-09-02 20:55
Did you solve this issue?

**Comment by samiragol** [comment] 2020-09-02 22:27
no unfortunatly I am still looking for solution. I am going to try different node versions to see if it will work

**Comment by samiragol** [comment] 2020-09-03 15:59
I also was using a different node.js version that Electron was. so I installed node.js version is the same as the version of Electron is using (12.16.3)  and that solve the problem

**Comment by risenW** [comment] 2020-09-03 17:54
That's great, I'll go ahead and close this issue now.

**Closed by risenW** 2020-09-03 17:54 UTC
