### ISSUE TITLE
not be able to query data after reading from csv

### ISSUE THREAD

**Issue by samiragol** [opensource9ja/danfojs#22] opened 2020-09-08 20:50 UTC
I am reading data from a csv file. I want to query data with a very simple statement: 

```
dfd.read_csv(dataPath)
.then(df => {
  let query_df = df.query({ column: "A", is: "==", to: "foo"});
  query_df.print();
})
``` 

it gives me this error: ``` ReferenceError: bar is not defined ``` and "bar" is one of the values in column "A"

**Comment by JhennerTigreros** [comment] 2020-09-10 01:18
Can you provide some rows of example from csv?

**Comment by samiragol** [comment] 2020-09-10 01:20
I used the same example in your github. 

```let data = { "Abs": [20, 30, 47] ,
            "Count": [34, 4, 5] ,
            "country code": ["NG", "FR", "GH"] }
```

**Comment by JhennerTigreros** [comment] 2020-09-10 01:37
Yes, the problem is in eval function that is used in frame.js

```js
if (eval(`${elem}${operator}${value}`)) {
  new_data.push(data_value);
  new_index.push(index[i]);
}
```
becase eval function resolve the string to `NG==NG` and the engine try to get the variable NG that doesn't exits, I fix this changing the snippet code to 

```js
if (eval(`elem${operator}value`)) {
  new_data.push(data_value);
  new_index.push(index[i]);
}
```

and get the correct output

![image](https://user-images.githubusercontent.com/32320832/92671503-11962180-f2dc-11ea-821d-827b97c6c25a.png)

change it locally while fixing on main branch, the file is in /danfojs-node/dist/core/frame.js

**Comment by samiragol** [comment] 2020-09-10 01:55
thanks, is it going to be in the next release?

**Comment by JhennerTigreros** [comment] 2020-09-10 02:19
I open a pull request with the fix :)

**Comment by risenW** [comment] 2020-09-10 12:48
@JhennerTigreros  
Thanks for the fix. Will take a look and merge.

**Comment by risenW** [comment] 2020-09-10 12:51
Merged! Thanks folks

**Closed by risenW** 2020-09-10 12:51 UTC

**Comment by fredthedead** [comment] 2020-12-08 12:05
I'm using the version suggested in the repository README.md file
` <script src="https://cdn.jsdelivr.net/npm/danfojs@0.1.2/dist/index.min.js"></script>`
and still getting this error... is this version the latest or is there a new one?
